swagger: '2.0'
info:
  description: 'IdentityChain Agency REST API'
  title: IdentityChain Agency API
  version: '0.0.1'
basePath: /ca/api
schemes:
  - http
securityDefinitions:
  basic:
    type: basic
consumes:
  - application/json
produces:
  - application/json
definitions:
  service_post:
    type: object
    properties:
      senderDid:
        type: string
      senderVerKey:
        type: string
      type:
        type: string
      data:
        type: object
        properties:
            targetDid:
              description: '(optional) Required if type=getUrl. Contains TargetDid for which the new URL inbox is requested' 
              type: string 
            token: 
              description: '(optional) Required if type=register. Contains Firebase Token to be created or updated at Agency side'
              type: string   
    required:
      - senderDid
      - senderVerKey
      - type
      - data
  inbox_post:
    type: object
    properties:
      message:
        description: 'Anoncrypted Message from other Edge Agents to be forwarded to mobile client'
        type: string
paths:
  /messages/{id}/:
    parameters:
      - description: A unique string value identifying this message. This request is usually sent to clients through FCM.
        in: path
        name: id
        required: true
        type: string
    get:
      summary: Retrieve a message
      description: Retrieve a message
      responses:
        '200':
          description: ''
      tags:
        - messages
  /services/:
    post:
      summary: Send a service request
      description: Send a service request
      parameters:
        - in: body
          name: data
          schema:
            $ref: '#/definitions/service_post'
      responses:
        '201':
          description: ''
      tags:
        - service
  /inbox/{id}:
    post:
      summary: Send a message to a mobile client using the unique URL endpoint provided by mobile edge agent.
      description: Create a credential definition
      parameters:
        - in: path
          name: id
          required: true
          description: A unique id usually provided by the mobile edge agent as the endpoint to this agency.
        - in: body
          name: message
          schema:
            $ref: '#/definitions/inbox_post'
      responses:
        '200':
          description: ''
      tags:
        - inbox